### ISSUE TITLE
Add Rob Christman blog and podcast

### ISSUE THREAD

**Issue by cbelsole** [etewiah/awesome-real-estate#1]
I am not affiliated with Rob Christman's blog or podcast. I've been following them for a while and there's a lot of good info for lending and the real estate industry.

Blog: https://www.robchrisman.com/
Podcast: https://open.spotify.com/show/3XsABmcuSD7vdYjfE8QlyO

**Comment by etewiah** [comment]
Thanks for that Chris.  The podcast does seem quite informative and useful so I've added it.   

The blog though.....  It is stuffed with ads and not very user friendly.  Sorry but I don't think it deserves a place here.

**Comment by cbelsole** [comment]
Totally fair. The blog has been around since 2008 and it needs an update for sure.

**Comment by etewiah** [comment]
Glad you understand ;) Hopefully Rob will update it sometime soon.
